// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewTG_2MMR45D9AHRgu-jW0aRaYxW3JCc',
    appId: '1:195571901335:web:fe319467ae169a61335ad2',
    messagingSenderId: '195571901335',
    projectId: 'woodcalc-ie3',
    authDomain: 'woodcalc-ie3.firebaseapp.com',
    storageBucket: 'woodcalc-ie3.appspot.com',
    measurementId: 'G-E42F8G5TRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhgL1FyM6-bqUJWzuYEYrIzIaz0moPydU',
    appId: '1:195571901335:android:cbec2767ee939a66335ad2',
    messagingSenderId: '195571901335',
    projectId: 'woodcalc-ie3',
    storageBucket: 'woodcalc-ie3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOVcUYyOAvu4ifNawLIjqjqTGmZM-8gk',
    appId: '1:195571901335:ios:a9d575b883e02ab9335ad2',
    messagingSenderId: '195571901335',
    projectId: 'woodcalc-ie3',
    storageBucket: 'woodcalc-ie3.appspot.com',
    iosBundleId: 'com.example.woodcalcIntE3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOVcUYyOAvu4ifNawLIjqjqTGmZM-8gk',
    appId: '1:195571901335:ios:90e372ac736552c3335ad2',
    messagingSenderId: '195571901335',
    projectId: 'woodcalc-ie3',
    storageBucket: 'woodcalc-ie3.appspot.com',
    iosBundleId: 'com.example.woodcalcIntE3.RunnerTests',
  );
}
